### ISSUE TITLE
Map request: Straight road with crosswalk and stoplines

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_xodr#26]
### Map request

![image](https://github.com/maliput/maliput_xodr/assets/53065142/f5ebb921-3ea5-40ab-ab79-4f0bad54fc82)

reference:

![image](https://github.com/maliput/maliput_xodr/assets/53065142/5f49ac13-c9c6-4e01-a85b-97935767d31d)

### Implementation suggestion

we need to place the stop line 7m in front of the crosswalk in GeoJSON and then split the lane in OpenDRIVE at the leading edge of the stop line.

**Comment by liangfok** [comment]
Among the various [map_request](https://github.com/maliput/maliput_xodr/labels/map_request) tickets, this one is highest priority.
