### ISSUE TITLE
Add OncommingTraffic properties in the template file instead of GeoJSON file

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_xodr#41]
### Summary
 - https://github.com/maliput/maliput_xodr/pull/39/ adds `OncomingTraffic` properties in the GeoJSON file directly for the: `resources/intersection/intersection_3_3m_width_6m_radius_stopline.geojson` resource
 
 ### Proposal

For consistency, we should make it part of the empy template file: https://github.com/maliput/maliput_xodr/blob/main/templates/intersection.xml.em

**Comment by francocipollone** [comment]
> Many thanks! I will close #39. Can you issue a new PR that does it the right way via modifying the template?

Will do!

**Comment by liangfok** [comment]
@francocipollone can this ticket be closed given https://github.com/maliput/maliput_xodr/commit/00330218267661fb3fdcf2b5b2d631822ca348ce?
