### ISSUE TITLE
Map Request: straight road with crosswalk, stop lines, and extended entry/exit

### ISSUE THREAD

**Issue by liangfok** [maliput/maliput_xodr#48]
This is the next iteration of #26. The only difference is the approach and exit distances are extended to 300m.

![straight_road_with_crosswalk_and_stop_lines_extended](https://github.com/maliput/maliput_xodr/assets/1388098/004bef68-e7e0-49df-84ff-4e239ba6cbbc)

Note the 300m of approach / exit stretches of straight road in both directions.
We can name this "**straight_road_with_crosswalk_and_stoplines_[number]m_wide_lanes**".

**Comment by francocipollone** [comment]
Hey @liangfok 
I noted that a width for the stop line is now required:

![image](https://github.com/maliput/maliput_xodr/assets/53065142/1157dc60-0961-45dd-8a21-5b9df9e2d149)

In the previous iteration wasn't required so it was just a line geoJSON-wise.

So let me ask: Is it a requirement on how the stop line should be informed in the geoJSON file? So instead of a line, it would be a polyline forming a rectangle of size `lane_width * stopline_width`

**Comment by francocipollone** [comment]
Oh actually it was part of the old scheme. However, the question is still valid I believe.

**Comment by liangfok** [comment]
Let's model the width of the stop line in the same manner as it was modeled previously in #35. In #35, the xodr view shows a dotted red box, while the geojson view shows a solid gray box. I believe this means the crosswalk was represented in both the xodr and geojson files. 

In the xodr file, I see: https://github.com/maliput/maliput_xodr/blob/3e7684fdeb864e2a595db7718a5612bb6f8034bd/resources/straight_forward/straight_forward_200m_3_5m_width_crosswalk_stopline.xodr#L183-L202

In the geojson, I see: https://github.com/maliput/maliput_xodr/blob/3e7684fdeb864e2a595db7718a5612bb6f8034bd/resources/straight_forward/straight_forward_200m_3_5m_width_crosswalk_stopline.xodr.geojson?short_path=3d59654#L3-L41

Since this design previously satisfied our user's needs, let's use the same design the same this time around. This only difference is the increased approach/exit distances. Instead of 200m end-to-end, it should now be 600m end-to-end. The crosswalk and stop line features should remain unchanged in the middle of this 600m long stretch of straight road.

**Comment by francocipollone** [comment]
Perfect. I believe then that #53 meets the requirements

**Comment by liangfok** [comment]
Great! I will review ASAP.

**Comment by francocipollone** [comment]
Closed as completed
